# Generated by Django 4.1.7 on 2023-04-02 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=2000)),
                ('starttime', models.DateTimeField(null=True)),
                ('endtime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoterId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voterid', models.IntegerField(default=0, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_voterid', to='camp.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Nominated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='nominatedimage/')),
                ('votecount', models.IntegerField(default=0, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_nominated', to='camp.campaign')),
            ],
        ),
    ]
