# Generated by Django 4.1.7 on 2023-04-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_campaign_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='camptype',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Multiple')], default='Single', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='endtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='starttime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='nominated',
            name='votecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voterid',
            name='voterid',
            field=models.IntegerField(default=0),
        ),
    ]
