# Generated by Django 4.1.7 on 2023-04-15 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_campaign_camptype_alter_campaign_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='endtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
