# Generated by Django 4.1.7 on 2023-04-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0004_alter_campaign_endtime_alter_campaign_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(null=True, upload_to='campimges/'),
        ),
    ]
