# Generated by Django 4.1.7 on 2023-04-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0007_alter_campaign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(null=True, upload_to='campimges/'),
        ),
    ]
