# Generated by Django 4.1.7 on 2023-04-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0008_alter_campaign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campimges/'),
        ),
        migrations.AlterField(
            model_name='nominated',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nominatedimage/'),
        ),
    ]
