# Generated by Django 4.1.7 on 2023-04-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0009_alter_campaign_image_alter_nominated_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
