# Generated by Django 4.1.7 on 2023-04-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0010_campaign_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
