# Generated by Django 4.1.7 on 2023-06-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0011_alter_campaign_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterid',
            name='voterid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
