# Generated by Django 4.1.7 on 2023-07-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0012_alter_voterid_voterid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterid',
            name='voterid',
            field=models.CharField(default=0, max_length=2000, unique=True),
        ),
    ]
