# Generated by Django 4.1.7 on 2023-07-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0013_alter_voterid_voterid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterid',
            name='voterid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
