# Generated by Django 4.1.7 on 2023-07-09 01:56

from django.db import migrations
import secured_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0014_alter_voterid_voterid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterid',
            name='voterid',
            field=secured_fields.fields.EncryptedIntegerField(default=0),
        ),
    ]
